### ISSUE TITLE
Duplication of reads with barcodes on +/- strand

### ISSUE THREAD

**Issue by nadiadavidson** [DavidsonGroup/flexiplex#2]
Give warning or find way to cut reads...

**Comment by andredsim** [comment]
Hi Nadia,

Thanks again for the tool. I was wondering if there was any progress on this particular issue? Would it be possible to add something to the read name that could be parsed?
For example [readid]_+1_of_3_*1_of_4
With the first two numbers being the current stranded label that is implemented, and the second two being ids including the extracted barcodes of the read from both strands? Then we can compare the 2nd and 4th number, and if they are different we know there was a duplication and can decide how we want to handle the read.

Kind Regards,
Andre
Goke Lab
