### ISSUE TITLE
Segfault when running with process substitution on MacOS

### ISSUE THREAD

**Issue by ChangqingW** [DavidsonGroup/flexiplex#26]
Not sure if this is worth investigating, but flexiplex seems to fail with segfault when running with process substitution on MacOS:
`./flexiplex -e 2 -f 8 -k <(curl -sL https://raw.githubusercontent.com/mritchielab/FLAMES/devel/inst/extdata/bc_allow.tsv.gz | zcat) <(curl -sL https://raw.githubusercontent.com/mritchielab/FLAMES/devel/inst/extdata/fastq/musc_rps24.fastq.gz | zcat)`
This could be reproduced from commit 27194e9 .
I can't do backtrace and debugging with the WEHI managed laptop.

**Comment by olliecheng** [comment]
I suspect it might be an issue with using a temporary pipe. Can you try this?

```
curl -sL https://raw.githubusercontent.com/mritchielab/FLAMES/devel/inst/extdata/bc_allow.tsv.gz | zcat > wl.txt
curl -sL https://raw.githubusercontent.com/mritchielab/FLAMES/devel/inst/extdata/fastq/musc_rps24.fastq.gz | zcat > fq.txt
./flexiplex -e 2 -f 8 -k wl.txt fq.txt
```

**Comment by ChangqingW** [comment]
Yeah saving them works, the segfault only occurs with bash process substitution on MacOS. The same line of code works fine on Linux.

**Comment by olliecheng** [comment]
And Zsh process substitution.

It seems particularly to be an error with the `-k` flag, as this works fine:
```sh
./flexiplex -e 2 -f 8 -k wl.txt <(curl -sL https://raw.githubusercontent.com/mritchielab/FLAMES/devel/inst/extdata/fastq/musc_rps24.fastq.gz | zcat)```
