### ISSUE TITLE
Dual barcodes

### ISSUE THREAD

**Issue by gwaldbieser** [DavidsonGroup/flexiplex#34]
Is it possible to demux barcodes on both ends of amplicons, and both strands? I suppose one can currently do it in a two-step approach to demux the 5'-end barcode then set up the second round to demux the 3'-end from each of the 5'-end subsets of files.
Or can this be done by using -b/-k to identify the 5' barcode and -u to denote the 3' barcode, even though they may be separated by several hundred bases?

**Comment by nadiadavidson** [comment]
Hi,
You should certainly be able to demultiplex the 5' and 3' separately, and this might even be possible with one line of bash (piping the output of one into another), depending on your reads and barcode structure. Treating the 3' as a UMI might also work, although we've never tried this with a gap of O(100bp) between. If you have some sample data (10-100 reads) you are happy to share, we are happy to advise on the best strategy for demultiplexing if you like.
Cheers,
Nadia.
