### ISSUE TITLE
Degenerate bases

### ISSUE THREAD

**Issue by cnk113** [DavidsonGroup/flexiplex#45]
Hi,

I was wondering if it was possible to allow a few degenerate bases in the primer sequences?

Best,
Chang

**Comment by olliecheng** [comment]
Hi Chang, thanks for your interest in Flexiplex. There are a couple different ways to do this, depending on what you’re looking for. Flexiplex supports using IUPAC degenerate base symbols (such as Y, R etc) as well as “any base” using `?` in both flanking sequences, if you know specifically where the degenerate/unknown bases are located in the wider primer sequence. Furthermore, Flexiplex allows for a more generic error-tolerant matching (using Levenshtein distance). To enable this for flanking sequences (such as primers), you can use the `-f x` parameter to enable an edit distance of `x` with the flanking sequences.

It is worth noting that by default, the flanking edit distance is 8. To disable this, use `-f 0`.

I hope that provides some clarity. If I haven’t addressed your question, an example sequence would be greatly appreciated!

Cheers
Ollie
