### ISSUE TITLE
Update documentation for flexiplex-filter

### ISSUE THREAD

**Issue by nadiadavidson** [DavidsonGroup/flexiplex#51]
- Update usage.md and README.md in scripts as filter-barcodes.py doesn't exist
- Update webpage doc - "scripts/flexiplex_filter/main.py". Should this be "python scripts/flexiplex_filter/main.py"?

**Comment by olliecheng** [comment]
Note to self: also add instructions to run straight from the web using `uvx`

**Comment by nadiadavidson** [comment]
Also... add which version range of python it will work for and any dependent packages needed (pandas etc.)

**Comment by olliecheng** [comment]
Fixed in #07ff4c and #0f49042.
