### ISSUE TITLE
flexiplex: command not found

### ISSUE THREAD

**Issue by lingminhao** [DavidsonGroup/flexiplex#6]
Hi @nadiadavidson , I just tried to use flexiplex and everything was fine until `cd flexiplex; make`. But when I use the command `flexiplex -k barcode_list.txt reads.fastq > new_reads.fastq`, I get the following error: `flexiplex: command not found`. What is the problem?

**Comment by nadiadavidson** [comment]
Hi, did you manage to resolve this? We are happy to help if not.

**Comment by lingminhao** [comment]
Hi @nadiadavidson , yes I solved this by putting `./` in front of `flexiplex`. Thanks!
