### ISSUE TITLE
Possibility of UMI deduplication from flexiplex output 

### ISSUE THREAD

**Issue by lingminhao** [DavidsonGroup/flexiplex#8]
Hi @nadiadavidson, I performed the cell barcode correction using flexiplex and got the fastq file & read CB UMI assignment as output. I realized that the UMI has not been corrected. Is there any plan to implement this into flexiplex or is there any other way?

**Comment by nadiadavidson** [comment]
Hi @lingminhao,
Flexiplex doesn't do any correction to the UMIs unfortunately and we don't have any immediate plans to add this, but it is a limitation we are aware of. 
Best of luck with your analysis,
Nadia.
